### ISSUE TITLE
Versions used to make it work

### ISSUE THREAD

**Issue by DavidWeiss2** [daehwa/Gait-Tracking-With-x-IMU-Python#1]
Hi, @daehwa, can you please refer to which python and libraries versions did you use?

I need to implement something very similar but not with steps but with a diving platform.
Can I rely on the data I extract as a plot as accurate for navigation precisely?

Best regards,
David W.

**Comment by daehwa** [comment]
Hi, @DavidWeiss2, Thanks for your questions.

1) About python and libraries versions:
I used python version of 3.7.1 and libraries versions 0.2.2 for ahrs, 1.1.0 for scipy, 3.2.1 for matplotlib, and 1.15.4 for numpy.

2) Navigation accuracy on a diving platform (in my opinion):
If it means human's steps when they step up the diving platform, I think this code would work for your data. You may need to change several parameters, such as `samplePeriod` and `filtCutOff`s for highpass and lowpass filters depending on sampling rates and walking behavior of your data.

This algorithm needs to initialize velocity to prevent drift when it detects 'stationary' (the stationary state is recognized in the filtered acceleration value). So, this code can be used when we can determine periodic stationary motions, like human footsteps. This code may not be accurate when you need to track diving (falling) motion.

I am looking forward to seeing your great work!

Thanks.

**Comment by oori** [comment]
For future reference, the key was forcing `ahrs < 0.3.0`
