### ISSUE TITLE
ahrs/common/orientation update

### ISSUE THREAD

**Issue by jsencak** [daehwa/Gait-Tracking-With-x-IMU-Python#3]
Hi, 
I encountered a traceback at line 116 in the file script.py. Can be solved by changing order of parameters
FROM: 
`acc.append(q_rot(np.array([x,y,z]), q_conj(q)))`
TO:
`acc.append(q_rot(q_conj(q), np.array([x,y,z])))`

I suppose it is caused by Python ahrs library update. I don't know when but the function q_rot defined in ahrs/common/orientation.py changed order of parameters. Solution is quite simple - just switch arguments. 

I appreciate your work, it helped me alot. 
Regards
Jakub

**Comment by daehwa** [comment]
Thank you so much for your suggestion!
Yes, I also have had the same issue and at that time I updated ahrs library.
Your suggestion will be very helpful for other people and also me!
