### ISSUE TITLE
The arguments in line 116 are swaped.

### ISSUE THREAD

**Issue by Rkk-10** [daehwa/Gait-Tracking-With-x-IMU-Python#6]
The arguments in line 116 are swaped causing a error in q_rot function. works after fixing.

Before--->    acc.append(q_rot( np.array([x, y, z]), q_conj(q)))
After----->    acc.append(q_rot(q_conj(q), np.array([x, y, z])))

......................................................................................................................................................................................................................................................................................

**Comment by daehwa** [comment]
Thank you so much for letting me know! In issue #3, I accepted a pull request and it was an inversed way. I guess it is a library version issue? Cause I provided library versions in one of the issues, I change line 116 again in order to prevent confusion. Thanks!
